on: [push]
name: Test variable substitution.

permissions:
      id-token: write
      contents: read

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: run PowerShell
        shell: pwsh
        run: M365DSC/TenantExport/TenantConfig.ps1
        env:
          CUSTOMER_NAME: ${{vars.CUSTOMER_NAME}}
          CUSTOMER_ID: ${{vars.CUSTOMER_ID}}
          TENANT_ID: ${{vars.TENANT_ID}}
          APPLICATION_NAME: ${{vars.APPLICATION_NAME}}
          APPLICATION_ID: ${{secrets.APPLICATION_ID}}
          CERTIFICATE_THUMBPRINT: ${{secrets.CERTIFICATE_THUMBPRINT}}

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd 